version: '3.6'

services:
  custom-gpts-paywall:
    build:
      context: .
    container_name: custom-gpts-paywall
    ports:
      - "8000:8000"  
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
    
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123  
      POSTGRES_DB: custom_gpts_paywall  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
