"""06_user_account_oauth2_support

Revision ID: 0ea5ee5a4cae
Revises: 8dd904135bd5
Create Date: 2023-12-21 12:12:33.458337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ea5ee5a4cae"
down_revision: Union[str, None] = "8dd904135bd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth_verification_request",
        sa.Column("state", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "oauth_verification_request",
        sa.Column("redirect_uri", sa.String(length=255), nullable=False),
    )
    op.add_column("user_account", sa.Column("client_id", sa.UUID(), nullable=False))
    op.add_column("user_account", sa.Column("client_secret", sa.UUID(), nullable=False))
    op.drop_column("user_account", "api_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account",
        sa.Column(
            "api_key", sa.VARCHAR(length=22), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("user_account", "client_secret")
    op.drop_column("user_account", "client_id")
    op.drop_column("oauth_verification_request", "redirect_uri")
    op.drop_column("oauth_verification_request", "state")
    # ### end Alembic commands ###
