"""08_add_user_table

Revision ID: 2bf907b56ce2
Revises: cb045f0e4cf1
Create Date: 2023-12-26 16:31:31.235154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2bf907b56ce2"
down_revision: Union[str, None] = "cb045f0e4cf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=22), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.rename_table("user_session", "gpt_session")
    op.create_index(
        op.f("ix_gpt_session_email"), "gpt_session", ["email"], unique=False
    )
    op.drop_index("ix_user_session_email", table_name="user_session")
    op.add_column(
        "custom_gpt_application", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "custom_gpt_application", "user", ["user_id"], ["id"])
    op.drop_column("custom_gpt_application", "email")
    op.drop_column("custom_gpt_application", "name")
    op.drop_column("custom_gpt_application", "store_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_gpt_application",
        sa.Column(
            "store_tokens",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "custom_gpt_application",
        sa.Column("name", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    )
    op.add_column(
        "custom_gpt_application",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "custom_gpt_application", type_="foreignkey")
    op.drop_column("custom_gpt_application", "user_id")
    op.rename_table("gpt_session", "user_session", "gpt_session")
    op.create_index("ix_user_session_email", "user_session", ["email"], unique=False)
    op.drop_index(op.f("ix_gpt_session_email"), table_name="gpt_session")
    op.drop_table("user")
    # ### end Alembic commands ###
