"""06_user_account_oauth2_support

Revision ID: 6c8aa336cfa9
Revises: 8dd904135bd5
Create Date: 2023-12-21 16:25:20.219147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c8aa336cfa9"
down_revision: Union[str, None] = "8dd904135bd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_account_id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_account_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "oauth_verification_request",
        sa.Column("state", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "oauth_verification_request",
        sa.Column("redirect_uri", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "user_account",
        sa.Column(
            "store_tokens",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("user_account", sa.Column("client_id", sa.UUID(), nullable=False))
    op.add_column("user_account", sa.Column("client_secret", sa.UUID(), nullable=False))
    op.drop_column("user_account", "api_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account",
        sa.Column("api_key", sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    )
    op.drop_column("user_account", "client_secret")
    op.drop_column("user_account", "client_id")
    op.drop_column("user_account", "store_tokens")
    op.drop_column("oauth_verification_request", "redirect_uri")
    op.drop_column("oauth_verification_request", "state")
    op.drop_table("oauth_token")
    # ### end Alembic commands ###
