"""02_add_custom_gpt_details

Revision ID: 7cf748fbb250
Revises: 2b422c447ac0
Create Date: 2023-11-27 00:21:47.028132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cf748fbb250"
down_revision: Union[str, None] = "2b422c447ac0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account", sa.Column("gpt_name", sa.String(length=30), nullable=False)
    )
    op.add_column(
        "user_account", sa.Column("gpt_description", sa.Text(), nullable=True)
    )
    op.add_column("user_account", sa.Column("gpt_url", sa.Text(), nullable=False))
    op.create_unique_constraint(None, "user_account", ["gpt_url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_account", type_="unique")
    op.drop_column("user_account", "gpt_url")
    op.drop_column("user_account", "gpt_description")
    op.drop_column("user_account", "gpt_name")
    # ### end Alembic commands ###
