"""04_allow_oauth_verification

Revision ID: 88e5239dd9be
Revises: ae1530fe8d07
Create Date: 2023-11-30 11:49:48.549751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "88e5239dd9be"
down_revision: Union[str, None] = "ae1530fe8d07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("verification_request", "email_verification_request")
    op.create_table(
        "oauth_verification_request",
        sa.Column("uuid", sa.String(length=22), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("authorization_code", sa.String(length=255), nullable=True),
        sa.Column("nonce", sa.String(length=22), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "CALLBACK_COMPLETED",
                "VERIFIED",
                "FAILED",
                "EXPIRED",
                "ARCHIVED",
                name="oauthverificationrequeststatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("oauth_flow_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "oauth_callback_completed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "user_account",
        "verification_medium",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.Enum(
            "Email", "Phone", "Google", name="verificationmedium", native_enum=False
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_account",
        "verification_medium",
        existing_type=sa.Enum(
            "Email", "Phone", "Google", name="verificationmedium", native_enum=False
        ),
        type_=sa.VARCHAR(length=5),
        existing_nullable=False,
    )
    op.rename_table("email_verification_request", "verification_request")
    op.drop_table("oauth_verification_request")
    # ### end Alembic commands ###
