"""05_add_archived_at

Revision ID: 8dd904135bd5
Revises: 88e5239dd9be
Create Date: 2023-12-20 11:17:05.420866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8dd904135bd5"
down_revision: Union[str, None] = "88e5239dd9be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_verification_request",
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_verification_request", "archived_at")
    # ### end Alembic commands ###
