"""03_allow_multiple_accounts_same_email

Revision ID: ae1530fe8d07
Revises: 7cf748fbb250
Create Date: 2023-11-27 14:44:43.743568

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ae1530fe8d07"
down_revision: Union[str, None] = "7cf748fbb250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_account_email_key", "user_account", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_account_email_key", "user_account", ["email"])
    # ### end Alembic commands ###
